### ISSUE TITLE
Failed to compile project with BLE api( x-nucleo-idb0xa1)

### ISSUE THREAD

**Issue by hudikm** [platformio/platform-freescalekinetis#1]
### Description of problem
When I tried to build example project [https://developer.mbed.org/teams/ST/code/BLE_HeartRate_IDB0XA1/](https://developer.mbed.org/teams/ST/code/BLE_HeartRate_IDB0XA1/) compilation failed.

Compilation fails on core file cmsis_nvic with pragma error:
```#error The target should define yotta config cmsis-nvic.has-vtor, or cmsis-nvic.has-custom-vtor + implement NVIC_SetVector/NVIC_GetVector_```
and fiew warnings that I should use c++11 standard.
After adding building flag -std=c++11 compilation ends with another error: 
```/home/martin/.platformio/packages/framework-mbed/drivers/RawSerial.cpp: In member function 'int mbed::RawSerial::printf(const char*, ...)':
/home/martin/.platformio/packages/framework-mbed/drivers/RawSerial.cpp:63:66: error: 'vsnprintf' was not declared in this scope
int len = vsnprintf(dummy_buf, sizeof(dummy_buf), format, arg);
```
### Configuration
Tested on:
platformio --version:
develop version: `PlatformIO, version 3.3.0a11`
stable version: `PlatformIO, version 3.2.1`
Platform versions:
```
freescalekinetis @ 1.6.0    
framework-mbed @ 3.131.0
toolchain-gccarmnoneeabi @ 1.40804.0
```
platformio.ini file:

```#Freescale FRDM Platform
[env:frdm_kl25z]
platform = freescalekinetis
framework = mbed
board = frdm_kl25z
build_flags = -std=c++11
lib_deps =
   x-nucleo-idb0xa1
```

**Comment by ivankravets** [comment]
Does it work with the latest upstream version? http://docs.platformio.org/en/latest/platforms/freescalekinetis.html#upstream

**Comment by ivankravets** [comment]
Please reopen if you still need help
