### ISSUE TITLE
Printk to console fails for freescale kinetis 8.2.0 (Zephyr 2.6.0) on FRDM-K64F

### ISSUE THREAD

**Issue by torge2** [platformio/platform-freescalekinetis#12]
**Problem Description**
Printk outputs are not sent to the console using Freescale Kinetis 8.2.0, Zephyr 2.6.0, PlatformIO Core 5.20 (Home 3.3.4). Platform is FRDM-K64F. 

**To Reproduce**
1. Install most recent PlatformIO v.2.3.3 in VS Studio Code (Core 5.2.0, Home 3.3.4).
2. Install Platfrom "Freescale Kinetis", ver. 8.2.0
3. Try a blinky App and additionally add one line of code at the beginning of main:
_printk("hello world! %s\n", CONFIG_BOARD);_
4. prj.conf looks like
CONFIG_GPIO=y
CONFIG_SERIAL=y
5. build and upload to FRDM-K64F

**Expected behavior**
Green LED should start blinking, "hello world! ..." should be seen in console .
**Received behavior**
The green LED is blinking only if CONFIG_SERIAL=n. LED is not blinking if CONFIG_SERIAL=y, printk statements are sent to console in no case.

**Workaround**
Using the FRDM-K64F controller with the same simple application (blinky + "HelloWorld") is working with Freescale Kinetis 8.1.0, Zephyr 2.5.0. LED is blinking properly, printk statements are sent to the console.

**Impact**
Without logging statements to the console application development is more complicated.

**console output**
No output.

**Environment**
 - OS: Windows 10
 - PlatformIO v.2.3.3 (Core 5.2.0), Zephyr 2.6.0, Freescale Kinetis 8.2.0
 - FRDM-K64F

**NOTE**
Problem [printk to console fails for freescale kinetis 8.2.0 (Zephyr 2.6.0) on FRDM-K64F · Issue #38631 · zephyrproject-rtos/zephyr (github.com)](https://github.com/zephyrproject-rtos/zephyr/issues/38631)
was closed with the note to file this problem in this community.
Problem also described in https://community.platformio.org/t/printk-to-console-fails-for-freescale-kinetis-8-2-0-zephyr-2-6-0-on-frdm-k64f/23732

**NOTE2**
Problem seems to be fixed with closed problems #38631 via #39452 in Zephyr. Problem was an order issue.

**Comment by tux19** [comment]
This can be closed, as it is fixed here https://github.com/zephyrproject-rtos/zephyr/issues/38631

**Comment by valeros** [comment]
Should be resolved in the platform v9.0.0 that uses the latest Zephyr v2.7.0.
