### ISSUE TITLE
** [upload] /dev/ttyACM0/firmware.bin: Not a directory

### ISSUE THREAD

**Issue by khoa-io** [platformio/platform-freescalekinetis#5]
Hi all.
I'm trying to run an example on a Freescale board. Building is OK but I can't upload file to the board.
Here is my upload command and its output:
```
pio run --target upload --upload-port /dev/ttyACM0 -v
[Thu Aug 17 20:47:00 2017] Processing frdm_kl46z (platform: freescalekinetis; upload_port: /dev/ttyACM0; board: frdm_kl46z; framework: mbed)
---------------------------------------------------------------------------------------------------------
Collected 22 compatible libraries
Looking for dependencies...
Project does not have dependencies
MethodWrapper(["upload"], [".pioenvs/frdm_kl46z/firmware.bin"])
Use manually specified: /dev/ttyACM0
MethodWrapper(["upload"], [".pioenvs/frdm_kl46z/firmware.bin"])
*** [upload] /dev/ttyACM0/firmware.bin: Not a directory
======================================= [ERROR] Took 1.32 seconds =======================================
```
I searched a lot on Google but there's no information can help me. So I create an issue here.
Thank you!

**Comment by ivankravets** [comment]
this board should have media disk. Upload port should be a path to it.

**Comment by khoa-io** [comment]
I don't think this board have one. This is output of `ls -la /dev/ttyACM0`:
```
crw-rw----. 1 root dialout 166, 0 Aug 17  2017 /dev/ttyACM0
```
It's a character device!
p/s: Link from board: [freescale.com/FRDM-KL46Z](freescale.com/FRDM-KL46Z).

**Comment by khoa-io** [comment]
If I don't specify `--upload-port /dev/ttyACM0` then following error happens:
```Looking for upload disk...
Error: Please specify `upload_port` for environment or use global `--upload-port` option.
For some development platforms it can be a USB flash drive (i.e. /media/<user>/<device name>)
*** [upload] Explicit exit, status 1
```

**Comment by Iambecomeroot** [comment]
For anyone else having this issue, I had to mount the drive in order to flash it. Check in something like `gnome-disks` if you have a drive show up and mount it. Platformio should find it when you try to upload agian.

**Comment by ivankravets** [comment]
@Iambecomeroot thanks for the solution!
